openapi: 3.0.0
info:
  title: PowerPlay API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /event:
    get:
      summary: Retrieves a list of ALL archived events
      description: Returns a list of ALL archived events.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    id:
                      type: integer
                    chairId:
                      type: string
                    timestamp:
                      type: string
                      format: date-time
                    version:
                      type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
